private["_filter"];
_filter = [_this,0,0,[0]] call BIS_fnc_param;
ctrlSetText[3103,"Police Clothing Shop"];
switch (_filter) do
{
	case 0: {[["A3L_PDOFC","Patrol Officer Uniform",10],["A3L_PDCPL","Patrol Corporal Uniform",10],["A3L_PDSGT","Patrol Sergeant Uniform",10],["A3L_PDLT","Patrol Lieutenant Uniform",10],["A3L_PDCPT","Patrol Captain Uniform",10],["A3L_PDCHIEF","Police Chief Uniform",10],["A3L_PDASSTCHIEF","Asst. Police Chief Uniform",10],["A3L_HPCPL","State Corporal Uniform",10],["A3L_HPSGT","State Sergeant Uniform",10],["A3L_HPLT","State Lieutenant Uniform",10],["A3L_HPCPT","State Captain Uniform",10],["TCG_PDDTC","Detective Uniform",10],["A3L_DAI","DA Investigator Uniform",10],["jamie_tou","SERT Uniform (Black)",10],["A3L_SWAT","SERT Uniform (Blue)",10],["A3L_COFC","Corrections Officer Uniform",10],["A3L_CCPL","Corrections Corporal Uniform",10],["A3L_CSGT","Corrections Sergeant Uniform",10],["A3L_CLT","Corrections Lieutenant Uniform",10],["A3L_CCPT","Corrections Captain Uniform",10]];};
	case 1: {[["jamie_pcapblack","Black Police Cap",10],["jamie_pcapblue","Blue Police Cap",10],["jamie_pcapblue2","Blue Police Cap",10],["Campaign_Hat_Dark","Campaign Hat (Black)",10],["Campaign_Hat_Washedout","Campaign Hat (Dark Brown)",10],["Campaign_Hat_Light","Campaign Hat (Light Brown)",10],["Campaign_Hat_Tan","Campaign Hat (Tan)",10],["TCG_swathelmet","SRU Helmet",10]];};
	case 2: {[["G_Aviator",nil,10],["G_Shades_Black",nil,10],["G_Shades_Blue",nil,10],["G_Sport_Blackred",nil,10],["G_Sport_Checkered",nil,10],["G_Sport_Blackyellow",nil,10],["G_Sport_BlackWhite",nil,10],["G_Squares",nil,10],["G_Lowprofile",nil,10],["G_Combat",nil,10],["G_Balaclava_blk",nil,10],["G_Balaclava_combat",nil,10],["G_Balaclava_lowprofile",nil,10],["A3L_Balaclava","Balaclava (Full Cover)",10]];};
	case 3: {[["jamie_black","Black Police Vest",10],["jamie_blacky2","Black Police Vest",10],["jamie_reflective","Reflective Police Vest",10],["TFO_TACVEST_POLICE","Task Force Vest",10],["DA_DUTY_VEST","DA Duty Vest",10],["DAI_VEST_TAN","DA Investigator Vest",10],["DAI_VEST_BLACK","DA Investigator Vest",10],["DAI_TACVEST_YELLOW","DAI Tactical Vest",10],["DAI_TACVEST_WHITE","DAI Tactical Vest",10],["IA_VEST_WHITE","Internal Affairs Vest",10],["IA_VEST_BLACK","Internal Affairs Vest",10],["jamie_corrections_vest","Corrections Vest",10],["jamie_security","Security Vest",10],["V_Press_F","Press Vest",10]];};
	case 4: {[["FFG_PoliceBelt","Duty Belt",10],["FFG_PoliceBeltdrop","Drop Holster Belt",10],["FFG_PoliceBeltINV","Invisible Duty Belt",10],["B_AssaultPack_cbr",nil,10],["B_Kitbag_mcamo",nil,10],["B_TacticalPack_oli",nil,10],["B_FieldPack_ocamo",nil,10],["B_Bergen_sgg",nil,10],["B_Kitbag_cbr",nil,10],["B_Carryall_oli",nil,10],["B_Carryall_khk",nil,10]];};
};